### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by A1exey1337** [Xzavier0722/SlimeGlue#24]
无法启动SlimeGlue

## Environment  / 环境
Slimefun version / 粘液科技版本: 2023.02 release
Plugin version / 插件版本: SlimeGlue-1.0.1-5538817.jar
OS / 操作系统: Windows10
Server brand / 服务器核心 (Spigot/Paper/etc.): paper-1.16.5-794
Server version / 服务器版本: 1.16.5
Plugin list / 插件列表: GrimAntiAC,Gsit,Slimefun,AlonsoLevels,AntiRedstoneClock,ChatEmojis,AntiSeedCracker,Litebans,Multiverse-Core,WorldEdit,Viaversion,XConomy,LiteSignin,ProtocolLib,LuckPerms,LaggRemover,SuperVanish,PlugManX,LockettePro,EssentialsX,MiaoBoard,Vault,PlaceholderAPI,ViaRewind,ViaBackwards,QuickShop
报错：[19:41:14] [Server thread/ERROR]: Error occurred while enabling SlimeGlue v1.0.1-5538817 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event com.xzavier0722.mc.plugin.slimefuncomplib.event.CargoWithdrawEvent. Static getHandlerList method required!
	at org.bukkit.plugin.SimplePluginManager.getRegistrationClass(SimplePluginManager.java:720) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:657) ~[patched_1.16.5.jar:git-Paper-794]
	at com.xzavier0722.mc.plugin.slimeglue.SlimeGlue.onEnable(SlimeGlue.java:40) ~[?:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:370) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:500) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:518) ~[patched_1.16.5.jar:git-Paper-794]
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:432) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:599) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:1074) ~[patched_1.16.5.jar:git-Paper-794]
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$a$0(MinecraftServer.java:291) ~[patched_1.16.5.jar:git-Paper-794]
	at java.lang.Thread.run(Thread.java:833) [?:?]

**Comment by Xzavier0722** [comment]
请将粘液本体与粘液胶均升级至exp版本后确认是否修复。
