### ISSUE TITLE
[BUG] 1.20.1 启动时报错

### ISSUE THREAD

**Issue by XXY233** [Xzavier0722/SlimeGlue#37]
## Description / 描述
插件在启动时报错。

```
[18:01:24 INFO]: [SlimeGlue] Enabling SlimeGlue v1.0.2-0543427
[18:01:24 INFO]: [SlimeGlue] ====SlimeGlue Start====
[18:01:24 INFO]: [SlimeGlue] - Loading modules...
[18:01:24 INFO]: [SlimeGlue] Loading compatibility module for Magic
[18:01:24 INFO]: [SlimeGlue] Loading compatibility module for LockettePro
[18:01:24 WARN]: [SlimeGlue] Plugin LockettePro is not installed or enabled, module ignored.
[18:01:24 INFO]: [SlimeGlue] Loading compatibility module for Residence
[18:01:24 WARN]: [SlimeGlue] Plugin Residence is not installed or enabled, module ignored.
[18:01:24 INFO]: [SlimeGlue] Loading compatibility module for Quickshop
[18:01:24 WARN]: [SlimeGlue] Plugin Quickshop is not installed or enabled, module ignored.
[18:01:24 INFO]: [SlimeGlue] Loading compatibility module for Kingdoms
[18:01:24 WARN]: [SlimeGlue] Plugin Kingdoms is not installed or enabled, module ignored.
[18:01:24 INFO]: [SlimeGlue] - Registering listeners...
[18:01:24 INFO]: [SlimeGlue] - Compatible Slimefun detected, enabling advanced features...
[18:01:24 ERROR]: Error occurred while enabling SlimeGlue v1.0.2-0543427 (Is it up to date?)
org.bukkit.plugin.IllegalPluginAccessException: Unable to find handler list for event com.xzavier0722.mc.plugin.slimefuncomplib.event.CancellableEvent. Static getHandlerList method required!
        at io.papermc.paper.plugin.manager.PaperEventManager.getRegistrationClass(PaperEventManager.java:124) ~[paper-1.20.1.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperEventManager.getRegistrationClass(PaperEventManager.java:122) ~[paper-1.20.1.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperEventManager.registerEvents(PaperEventManager.java:84) ~[paper-1.20.1.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.registerEvents(PaperPluginManagerImpl.java:131) ~[paper-1.20.1.jar:git-Paper-47]
        at org.bukkit.plugin.SimplePluginManager.registerEvents(SimplePluginManager.java:670) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at com.xzavier0722.mc.plugin.slimeglue.SlimeGlue.loadCompOnlyFeatures(SlimeGlue.java:124) ~[SlimeGlue-exp-0543427.jar:?]
        at com.xzavier0722.mc.plugin.slimeglue.SlimeGlue.onEnable(SlimeGlue.java:46) ~[SlimeGlue-exp-0543427.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[paper-1.20.1.jar:git-Paper-47]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.1.jar:git-Paper-47]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugin(CraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-47]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.enablePlugins(CraftServer.java:547) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:636) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:435) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1101) ~[paper-1.20.1.jar:git-Paper-47]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:318) ~[paper-1.20.1.jar:git-Paper-47]        at java.lang.Thread.run(Thread.java:833) ~[?:?]
[18:01:24 INFO]: [SlimeGlue] Disabling SlimeGlue v1.0.2-0543427
```

## Environment  / 环境
Slimefun version / 粘液科技版本: ec3ce86-DEV
Plugin version / 插件版本: v1.0.2-0543427
OS / 操作系统: Windows 11 22H2
Server brand / 服务器核心 (Spigot/Paper/etc.): Paper git-Paper-47 (MC: 1.20.1)
Server version / 服务器版本: 1.20.1

**Comment by Xzavier0722** [comment]
本件是由于粘液中文版本体依赖了错误的comp lib版本，已在粘液本体内测版修复。如果你是内测用户请等待频道更新，否则请留意粘液中文版的公测更新。
