### ISSUE TITLE
[BUG]粘液书打不开，闪报错

### ISSUE THREAD

**Issue by DenNotFound** [Xzavier0722/SlimeGlue#9]
## Description / 描述
Please describe the issue in detail. 
请详细描述遇到的问题。 粘液胶和王国放一起粘液书打不开

## Environment  / 环境
Slimefun version / 粘液科技版本:c97d6a5-canary
Plugin version / 插件版本:KingdomsX1.13.0.1
OS / 操作系统:windows 10
Server brand / 服务器核心 (Spigot/Paper/etc.):paper1.18
Server version / 服务器版本:1.18.2
Plugin list / 插件列表:slimefun slimeglue kingdomsX
报错[15:36:41 ERROR]: [dough: protection] An Error occured while querying the Protection Module: "SlimeGlue v1.0.0-df6c18d"
java.lang.NoClassDefFoundError: org/kingdoms/constants/land/location/SimpleChunkLocation
        at com.xzavier0722.mc.plugin.slimeglue.module.KingdomsXModule.canAccess(KingdomsXModule.java:52) ~[SlimeGlue-exp-df6c18d (1).jar:?]
        at com.xzavier0722.mc.plugin.slimeglue.module.KingdomsXModule.access$000(KingdomsXModule.java:13) ~[SlimeGlue-exp-df6c18d (1).jar:?]
        at com.xzavier0722.mc.plugin.slimeglue.module.KingdomsXModule$1.canBreakBlock(KingdomsXModule.java:24) ~[SlimeGlue-exp-df6c18d (1).jar:?]
        at com.xzavier0722.mc.plugin.slimeglue.slimefun.GlueProtectionModule.hasPermission(GlueProtectionModule.java:34) ~[SlimeGlue-exp-df6c18d (1).jar:?]
        at io.github.thebusybiscuit.slimefun4.libraries.dough.protection.ProtectionManager.hasPermission(ProtectionManager.java:174) ~[Slimefun-vc97d6a5-canary.jar:?]
        at io.github.thebusybiscuit.exoticgarden.listeners.PlantsListener.onInteract(PlantsListener.java:362) ~[ExoticGarden-Build 8 zh-CN(ybw0014) (git e13294a).jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor376.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:75) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:git-Paper-295]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:663) ~[paper-api-1.18.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_18_R2.event.CraftEventFactory.callPlayerInteractEvent(CraftEventFactory.java:544) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.server.level.ServerPlayerGameMode.useItemOn(ServerPlayerGameMode.java:552) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.handleUseItemOn(ServerGamePacketListenerImpl.java:1851) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.handle(ServerboundUseItemOnPacket.java:33) ~[?:?]
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.a(ServerboundUseItemOnPacket.java:9) ~[?:?]
        at net.minecraft.network.protocol.PacketUtils.lambda$ensureRunningOnSameThread$1(PacketUtils.java:51) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:23) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1399) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:188) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1376) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1369) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1447) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1225) ~[paper-1.18.2.jar:git-Paper-295]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:315) ~[paper-1.18.2.jar:git-Paper-295]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.kingdoms.constants.land.location.SimpleChunkLocation
        ... 30 more

**Comment by DenNotFound** [comment]
啊忘了写粘液胶版本了
SlimeGlue-1.0.0-6fe657a
